### ISSUE TITLE
Crash when using menu item Edit Quick-Expires Now

### ISSUE THREAD

**Issue by MichiFr** [Rookiestyle/KPColorChange#3]
Hi,

I notice Keepass 2.46 to be crashed when using menu Entry -> Edit Entry (Quick) -> Expires: Now and KPColorChange 2.2 is active. 
![2020-12-26_091743](https://user-images.githubusercontent.com/28045390/103148838-42537700-4764-11eb-8452-5b8ede6014b5.jpg)

Steps to reproduce: 
1. KPColorChange is active, which means the toolbar button is pressed to hide expired entries.
2. Select a few entries to be set to expire
3. Use menu  _Entry -> Edit Entry (Quick) -> Expires: Now_
4. Or: Use context menu: _Edit Entry (Quick) -> Expires: Now_
5. Keepass crashes with an unhandled exception: Invalid Argument: Value -1 is invalid for index...Parametername: index

Could you pls check?

Thanks,
Michael

**Comment by Rookiestyle** [comment]
Thanks for reporting this, I fixed the bug in KPColorChange.

With only KPcolorChange installed, this bug would have resulted in a frozen entry list. The error message in your screenshot is because of a different plugins having issues as well.

If you're using [ColoredPassword](/Rookiestyle/ColoredPassword): I released a fix for this plugin as well

If you're using a different plugin, please create an issue in the respective plugin's issue tracker.
The "Details" Button in your screenshot might help identifying the affected plugin

**Comment by MichiFr** [comment]
Thanks for the update and yes, I used ColoredPassword as well. Bug is fiexed now! Thanks for this ultra fast fix - have a nice X-max holiday!
